---
trust-domain: xpi

task-priority: lowest

taskgraph:
    register: xpi_taskgraph:register
    repositories:
        # This is the manifest repo
        # string: for a source repo, this should match the `repo-prefix`
        #         in `xpi-manifest.yml`
        xpi:
            # string: the name of the repo, for humans
            name: "XPI manifest"
            # regex: to match the base name of the repo
            project-regex: xpi-manifest
            # string: the repo url. Use `git@github.com:org/repo` for private
            #         repositories.
            default-repository: https://github.com/mozilla-extensions/xpi-manifest
            # string: which branch is primary; should be `master`
            default-ref: master
            # enum: hg or git; should be `git`
            type: git
        template:
            name: "template repo test"
            project-regex: test-xpi-public$
            default-repository: https://github.com/escapewindow/test-xpi-public
            default-ref: master
            type: git
        normandydevtools:
            name: "Normandy Devtools"
            project-regex: normandy-devtools$
            default-repository: https://github.com/mozilla-extensions/normandy-devtools
            default-ref: master
            type: git
        remotesettingsdevtools:
            name: "Remote Settings Devtools"
            project-regex: remote-settings-devtools$
            default-repository: https://github.com/mozilla-extensions/remote-settings-devtools
            default-ref: master
            type: git
        searchenginedevtools:
            name: "Search Engine Devtools"
            project-regex: searchengine-devtools$
            default-repository: https://github.com/mozilla-extensions/searchengine-devtools
            default-ref: master
            type: git
        httpsupgradestudyv2:
            name: "HTTPS Upgrade Study (v2)"
            project-regex: https-upgrade-study-v2$
            default-repository: git@github.com:mozilla-extensions/https-upgrade-study-v2
            default-ref: master
            type: git
        cpmanager:
            name: "MozillaOnline cpmanager"
            project-regex: cpmanager$
            default-repository: git@github.com:mozilla-extensions/cpmanager
            default-ref: master
            type: git
        cehomepage:
            name: "MozillaOnline cehomepage"
            project-regex: cehomepage$
            default-repository: git@github.com:mozilla-extensions/cehomepage
            default-ref: master
            type: git
        pioneerv2example:
            name: "Pioneer v2 Example"
            project-regex: pioneerv2example$
            default-repository: git@github.com:mozilla-extensions/pioneer-v2-example
            default-ref: master
            type: git
        chinanewtab:
            name: "MozillaOnline China New Tab"
            project-regex: china-newtab$
            default-repository: https://github.com/mozilla-extensions/china-newtab
            default-ref: master
            type: git
        loginstudy:
            name: "Login Study"
            project-regex: login-study$
            default-repository: https://github.com/mozilla-extensions/login-study
            default-ref: master
            type: git

    cached-task-prefix: xpi

workers:
    aliases:
        b-linux:
            provisioner: xpi-{level}
            implementation: docker-worker
            os: linux
            worker-type: 'b-linux'
        images:
            provisioner: xpi-{level}
            implementation: docker-worker
            os: linux
            worker-type: 'images'
        dep-signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: scriptworker
            worker-type: xpi-t-signing
        signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: scriptworker
            worker-type:
                by-level:
                    "3": xpi-3-signing
                    default: xpi-t-signing
        shipit:
            provisioner: scriptworker-k8s
            implementation: scriptworker-shipit
            os: scriptworker
            worker-type:
                by-level:
                    "3": xpi-3-shipit
                    default: xpi-1-shipit

github_clone_secret: project/xpi/xpi-github-clone-ssh

scriptworker:
    scope-prefix: project:xpi:releng
    signing-format:
        by-xpi-type:
            privileged: privileged_webextension
            system: system_addon
            mozillaonline-privileged: privileged_webextension

release-promotion:
    flavors:
        build:
            target-tasks-method: build_xpi
            rebuild-kinds:
                - build
                - test
                - dep-signing
        promote:
            target-tasks-method: promote_xpi
    notifications:
        # configure privileged webextension email addresses for
        # notifications
        privileged:
            by-phase:
                build:
                    - "aki+priv-webext-build@mozilla.com"
                    - "rdalal+priv-webext-build@mozilla.com"
                    - "awagner+priv-webext-build@mozilla.com"
                    - "mcooper+priv-webext-build@mozilla.com"
                promote:
                    - "aki+priv-webext-promote@mozilla.com"
                    - "rdalal+priv-webext-promote@mozilla.com"
                    - "awagner+priv-webext-promote@mozilla.com"
                    - "mcooper+priv-webext-promote@mozilla.com"
        # configure system addons email addresses for notifications
        system:
            by-phase:
                build:
                    - "aki+system-addons-build@mozilla.com"
                    - "rdalal+system-addons-build@mozilla.com"
                    - "mcooper+system-addons-build@mozilla.com"
                promote:
                    - "aki+system-addons-promote@mozilla.com"
                    - "rdalal+system-addons-promote@mozilla.com"
                    - "mcooper+system-addons-promote@mozilla.com"
        # configure mozillaonline-privileged webextension email addresses for
        # notifications
        mozillaonline-privileged:
            by-phase:
                build:
                    - "aki+mozillaonline-priv-webext-build@mozilla.com"
                    - "hectorz+mozillaonline-priv-webext-build@mozilla.com"
                    - "mkaply+mozillaonline-priv-webext-build@mozilla.com"
                    - "awagner+mozillaonline-priv-webext-build@mozilla.com"
                promote:
                    - "aki+mozillaonline-priv-webext-promote@mozilla.com"
                    - "hectorz+mozillaonline-priv-webext-promote@mozilla.com"
                    - "mkaply+mozillaonline-priv-webext-promote@mozilla.com"
                    - "awagner+mozillaonline-priv-webext-promote@mozilla.com"
