---
trust-domain: xpi

task-priority: lowest

taskgraph:
    register: xpi_taskgraph:register
    repositories:
        # This is the manifest repo
        # string: for a source repo, this should match the `repo-prefix`
        #         in `xpi-manifest.yml`
        xpi:
            # string: the name of the repo, for humans
            name: "XPI manifest"
            # regex: to match the base name of the repo
            project-regex: xpi-manifest$
            # string: the repo url. Use `git@github.com:org/repo` for private
            #         repositories.
            default-repository: https://github.com/mozilla-extensions/xpi-manifest
            # string: which branch is primary; should be `master`
            default-ref: master
            # enum: hg or git; should be `git`
            type: git
        stagingpublic:
            name: "Releng staging repo test"
            project-regex: staging-xpi-public$
            default-repository: https://github.com/mozilla-releng/staging-xpi-public
            default-ref: master
            type: git
        stagingprivate:
            name: "Releng staging private repo test"
            project-regex: staging-xpi-private$
            default-repository: git@github.com:mozilla-releng/staging-xpi-private
            default-ref: master
            type: git
        normandydevtools:
            name: "Normandy Devtools"
            project-regex: normandy-devtools$
            default-repository: https://github.com/mozilla-extensions/normandy-devtools
            default-ref: main
            type: git
        remotesettingsdevtools:
            name: "Remote Settings Devtools"
            project-regex: remote-settings-devtools$
            default-repository: https://github.com/mozilla-extensions/remote-settings-devtools
            default-ref: master
            type: git
        searchenginedevtools:
            name: "Search Engine Devtools"
            project-regex: searchengine-devtools$
            default-repository: https://github.com/mozilla-extensions/searchengine-devtools
            default-ref: main
            type: git
        httpsupgradestudyv2:
            name: "HTTPS Upgrade Study (v2)"
            project-regex: https-upgrade-study-v2$
            default-repository: git@github.com:mozilla-extensions/https-upgrade-study-v2
            default-ref: master
            type: git
        cpmanager:
            name: "MozillaOnline cpmanager"
            project-regex: cpmanager$
            default-repository: git@github.com:mozilla-extensions/cpmanager
            default-ref: master
            type: git
        cehomepage:
            name: "MozillaOnline cehomepage"
            project-regex: cehomepage$
            default-repository: git@github.com:mozilla-extensions/cehomepage
            default-ref: master
            type: git
        pioneerv2example:
            name: "Pioneer v2 Example"
            project-regex: pioneerv2example$
            default-repository: git@github.com:mozilla-extensions/pioneer-v2-example
            default-ref: master
            type: git
        chinanewtab:
            name: "MozillaOnline China New Tab"
            project-regex: china-newtab$
            default-repository: https://github.com/mozilla-extensions/china-newtab
            default-ref: master
            type: git
        loginstudy:
            name: "Login Study"
            project-regex: login-study$
            default-repository: git@github.com:mozilla-extensions/login-study
            default-ref: master
            type: git
        webcompat:
            name: "Web Compat"
            project-regex: webcompat-addon$
            default-repository: https://github.com/mozilla-extensions/webcompat-addon
            default-ref: master
            type: git
        secureproxy:
            name: "Secure-Proxy"
            project-regex: secure-proxy$
            default-repository: https://github.com/mozilla-extensions/secure-proxy
            default-ref: master
            type: git
        firefoxvoice:
            name: "Firefox Voice"
            project-regex: firefox-voice$
            default-repository: https://github.com/mozilla-extensions/firefox-voice
            default-ref: prod
            type: git
        dohresolverusagestudy:
            name: "DoH Resolver Usage Study"
            project-regex: doh-resolver-usage-study$
            default-repository: https://github.com/mozilla-extensions/doh-resolver-usage-study
            default-ref: master
            type: git
        dnssecinterferencestudy:
            name: "DNSSEC Interference Study"
            project-regex: dnssec-interference-study$
            default-repository: https://github.com/mozilla-extensions/dnssec-interference
            default-ref: master
            type: git
        newsdisinformationstudy:
            name: "Princeton News Disinfo Study"
            project-regex: newsdisinformationstudy$
            default-repository: https://github.com/mozilla-extensions/news-disinformation-study
            default-ref: master
            type: git
        proxymonitor:
            name: "Proxy Monitor extension"
            project-regex: proxymonitor$
            default-repository: git@github.com:mozilla-extensions/proxy-monitor
            default-ref: main
            type: git
        rallycoreaddon:
            name: "Rally Core Add-on"
            project-regex: rallycoreaddon$
            default-repository: https://github.com/mozilla-rally/rally-core-addon
            default-ref: release
            type: git
        telemetrytestingextension:
            name: "Telemetry testing extension"
            project-regex: telemetrytestingextension$
            default-repository: https://github.com/mozilla-extensions/dynamic-probe-telemetry-extension
            default-ref: main
            type: git
        searchdefaultaddon:
            name: "Reset Search Default extension"
            project-regex: searchdefaultaddon$
            default-repository: https://github.com/mozilla-extensions/restore-search-defaults
            default-ref: main
            type: git
        quicksuggestweather:
            name: "Firefox Quick Suggest Weather"
            project-regex:  firefox-quick-suggest-weather$
            default-repository: git@github.com:mozilla-extensions/firefox-quick-suggest-weather
            default-ref: master
            type: git
        quicksuggestadm:
            name: "Firefox Quick Suggest Adm"
            project-regex:  firefox-quick-suggest-adm$
            default-repository: git@github.com:mozilla-extensions/firefox-quick-suggest-adm
            default-ref: master
            type: git
        quicksuggestcalculator:
            name: "Firefox Quick Suggest Calculator"
            project-regex:  firefox-quick-suggest-calculator$
            default-repository: https://github.com/mozilla-extensions/firefox-quick-suggest-calculator.git
            default-ref: master
            type: git
        balrogdryrun:
            name: "Balrog Dry Run"
            project-regex:  balrog-dryrun$
            default-repository: https://github.com/mozilla-extensions/balrog-dryrun.git
            default-ref: main
            type: git
        addonssearchdetection:
            name: "Add-ons Search Detection extension"
            project-regex: addonssearchdetection$
            default-repository: https://github.com/mozilla-extensions/addons-search-detection
            default-ref: main
            type: git


    cached-task-prefix: xpi

workers:
    aliases:
        b-linux:
            provisioner: xpi-{level}
            implementation: docker-worker
            os: linux
            worker-type: 'b-linux'
        images:
            provisioner: xpi-{level}
            implementation: docker-worker
            os: linux
            worker-type: 'images'
        dep-signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: scriptworker
            worker-type: xpi-t-signing
        github:
            provisioner: scriptworker-k8s
            implementation: scriptworker-github
            os: scriptworker
            worker-type: 'xpi-{level}-github'
        signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: scriptworker
            worker-type:
                by-level:
                    "3": xpi-3-signing
                    default: xpi-t-signing
        shipit:
            provisioner: scriptworker-k8s
            implementation: scriptworker-shipit
            os: scriptworker
            worker-type:
                by-level:
                    "3": xpi-3-shipit
                    default: xpi-1-shipit

github_clone_secret: project/xpi/xpi-github-clone-ssh

scriptworker:
    scope-prefix: project:xpi:releng
    signing-format:
        by-xpi-type:
            mozillaonline-privileged: privileged_webextension
            normandy-privileged: privileged_webextension
            privileged: privileged_webextension
            system: system_addon

release-promotion:
    flavors:
        build:
            target-tasks-method: build_xpi
            rebuild-kinds:
                - build
                - test
                - dep-signing
        promote:
            target-tasks-method: promote_xpi
        ship:
            target-tasks-method: ship_xpi
    notifications:
        # configure mozillaonline-privileged webextension email addresses for
        # notifications
        mozillaonline-privileged:
            by-phase:
                build:
                    - "aki+mozillaonline-priv-webext-build@mozilla.com"
                    - "hectorz+mozillaonline-priv-webext-build@mozilla.com"
                    - "mkaply+mozillaonline-priv-webext-build@mozilla.com"
                    - "awagner+mozillaonline-priv-webext-build@mozilla.com"
                promote:
                    - "aki+mozillaonline-priv-webext-promote@mozilla.com"
                    - "hectorz+mozillaonline-priv-webext-promote@mozilla.com"
                    - "mkaply+mozillaonline-priv-webext-promote@mozilla.com"
                    - "awagner+mozillaonline-priv-webext-promote@mozilla.com"
                ship:
                    - "aki+mozillaonline-priv-webext-ship@mozilla.com"
                    - "hectorz+mozillaonline-priv-webext-ship@mozilla.com"
                    - "mkaply+mozillaonline-priv-webext-ship@mozilla.com"
                    - "awagner+mozillaonline-priv-webext-ship@mozilla.com"
        # configure normandy-privileged webextension email addresses for
        # notifications
        normandy-privileged:
            by-phase:
                build:
                    - "aki+normandy-priv-webext-build@mozilla.com"
                    - "mcooper+normandy-priv-webext-build@mozilla.com"
                promote:
                    - "aki+normandy-priv-webext-promote@mozilla.com"
                    - "mcooper+normandy-priv-webext-promote@mozilla.com"
                ship:
                    - "aki+normandy-priv-webext-ship@mozilla.com"
                    - "mcooper+normandy-priv-webext-ship@mozilla.com"
        # configure privileged webextension email addresses for notifications
        privileged:
            by-phase:
                build:
                    - "privileged-addon-reviewers+shipit-build@mozilla.com"
                promote:
                    - "privileged-addon-reviewers+shipit-promote@mozilla.com"
                ship:
                    - "privileged-addon-reviewers+shipit-ship@mozilla.com"
        # configure system addons email addresses for notifications
        system:
            by-phase:
                build:
                    - "aki+system-addons-build@mozilla.com"
                    - "awagner+system-addons-build@mozilla.com"
                    - "pkewisch+system-addons-build@mozilla.com"
                promote:
                    - "aki+system-addons-promote@mozilla.com"
                    - "awagner+system-addons-promote@mozilla.com"
                    - "pkewisch+system-addons-promote@mozilla.com"
                ship:
                    - "aki+system-addons-ship@mozilla.com"
                    - "awagner+system-addons-ship@mozilla.com"
                    - "pkewisch+system-addons-ship@mozilla.com"
