description: Firefox Translations
repo-prefix: firefoxtranslations
active: true
private-repo: false
additional-emails: ["anatal-all@mozilla.com"]
branch: release
artifacts:
  - web-ext-artifacts/firefox_translations.xpi
addon-type: privileged
install-type: npm
enable-github-release: true
