---
description: Firefox Newtab
repo-prefix: newtab
active: true
private-repo: false
branch: main
directory: browser/extensions/newtab
additional-emails: [mconley@mozilla.com]
artifacts:
  - web-ext-artifacts/newtab.xpi
addon-type: system
install-type: mach
enable-github-release: False
enable-test: False
