description: Extension asks users to reset their default search for some extensions
repo-prefix: searchdefaultaddon
active: true
private-repo: true
branch: main
artifacts:
  - web-ext-artifacts/reset-search-defaults.xpi
addon-type: privileged
install-type: npm
