---
description: Search Engine Devtools
repo-prefix: searchenginedevtools
branch: main
active: true
private-repo: false
artifacts:
  - web-ext-artifacts/searchengine-devtools.xpi
addon-type: privileged
install-type: npm
additional-emails: ["standard8@mozilla.com", "dharvey@mozilla.com"]
