description: Relaunch of Rally Search Engine Usage study extension
repo-prefix: searchengineusagestudyrelaunch
active: true
private-repo: false
branch: release
artifacts:
  - web-ext-artifacts/search_engine_usage_study.xpi
addon-type: privileged
install-type: npm
