description: Web Compat
repo-prefix: webcompat
active: true
private-repo: false
branch: release-hotfix
artifacts:
  - web-ext-artifacts/webcompat.xpi
addon-type: system
install-type: npm
enable-github-release: true
