description: Web Compat
repo-prefix: webcompat
active: true
private-repo: false
branch: main
directory: browser/extensions/webcompat
artifacts:
  - web-ext-artifacts/webcompat.xpi
addon-type: system
install-type: mach
enable-balrog: true
enable-github-release: false
enable-test: false
